(function() {
	'use strict';
	define([], function() {
		var enums = function() {
			return {

				features: {
					// Application Role
					// SM_APP_ROLE_GET: 'SM_APPLICATION_ROLE_GET',
					// SM_APP_ROLE_CREATE: 'SM_APPLICATION_ROLE_CREATE',
					// SM_APP_ROLE_UPDATE: 'SM_APPLICATION_ROLE_UPDATE',
					// SM_APP_ROLE_DELETE: 'SM_APPLICATION_ROLE_DELETE',
					// SM_APP_ROLE_FEATURES: 'SM_APPLICATION_ROLE_FEATURES',


					// Invoice

					'ND_DOC_TPL_GET': 'ND_DOCUMENT_TEMPLATE_GET',
					'ND_DOC_TPL_CREATE': 'ND_DOCUMENT_TEMPLATE_CREATE',
					'ND_DOC_TPL_UPDATE': 'ND_DOCUMENT_TEMPLATE_UPDATE',
					'ND_DOC_TPL_DELETE': 'ND_DOCUMENT_TEMPLATE_DELETE',
					'ND_DOC_TPL_SHARE': 'ND_DOCUMENT_TEMPLATE_SHARE',
					'ND_DOC_GET': 'ND_DOCUMENT_GET',
					'ND_DOC_CREATE': 'ND_DOCUMENT_CREATE',
					'ND_DOC_UPDATE': 'ND_DOCUMENT_UPDATE',
					'ND_DOC_DELETE': 'ND_DOCUMENT_DELETE',
					'ND_DOC_SHARE': 'ND_DOCUMENT_SHARE',

					// // User
					// SM_USER_GET: 'SM_USER_GET',
					// SM_USER_UPDATE: 'SM_USER_UPDATE',
					// SM_USER_ROLES: 'SM_USER_ROLES',
					// SM_USER_A_GET: 'SM_USER_ADMIN_GET',
					// SM_USER_A_DELETE: 'SM_USER_ADMIN_DELETE',


					// // Custmer
					// SM_CUSTOMER_GET: 'SM_CUSTOMER_GET',
					// SM_CUSTOMER_CREATE: 'SM_CUSTOMER_CREATE',
					// SM_CUSTOMER_UPDATE: 'SM_CUSTOMER_UPDATE',
					// SM_CUSTOMER_DELETE: 'SM_CUSTOMER_DELETE',
					// SM_CUSTOMER_MANAGE_USERS: 'SM_CUSTOMER_MANAGE_USERS',
				},

			};

		};

		return [enums];
	});
}());
